### ISSUE TITLE
Can't create folders or albums: "User has not granted the required permissions" 

### ISSUE THREAD

**Issue by firecat53** [graveljp/smugcli#20]
Any ideas? Same error for `mkalbum` and `mkdir`.
   
    $ smugcli mkalbum --privacy unlisted Family/2021/
    Creating Album "Family/2021".
    Traceback (most recent call last):
      File "/home/firecat53/.local/bin/smugcli", line 8, in <module>
        sys.exit(main())
      File "/home/firecat53/.local/lib/python3.9/site-packages/smugcli/smugcli.py", line 310, in main
        run(sys.argv[1:])
      File "/home/firecat53/.local/lib/python3.9/site-packages/smugcli/smugcli.py", line 302, in run
        parsed.func(parsed)
      File "/home/firecat53/.local/lib/python3.9/site-packages/smugcli/smugcli.py", line 118, in <lambda>
        func=lambda a, t=node_type: fs.make_node(a.user, a.path, a.p, t,
      File "/home/firecat53/.local/lib/python3.9/site-packages/smugcli/smugmug_fs.py", line 167, in make_node
        self._match_or_create_nodes(
      File "/home/firecat53/.local/lib/python3.9/site-packages/smugcli/smugmug_fs.py", line 102, in _match_or_create_nodes
        all_nodes.append(all_nodes[-1].get_or_create_child(dir, params))
      File "/home/firecat53/.local/lib/python3.9/site-packages/smugcli/smugmug.py", line 292, in get_or_create_child
        return self._create_child_node(name, params)
      File "/home/firecat53/.local/lib/python3.9/site-packages/smugcli/smugmug.py", line 253, in _create_child_node
        raise UnexpectedResponseError(
    smugcli.smugmug.UnexpectedResponseError: Error creating node "2021".
    Server responded with status code 401: The user has not granted the required permissions.

Sync, upload, and ls work great. 

I don't know if it matters, but my API key was issued back in 2011. ~/.smugcli shows a v2 endpoint: "authuser_uri": "/api/v2/node/7mTW5" so that may be irrelevant. I'm not sure when the v2 API started, but I think it was quite awhile ago...

**Comment by graveljp** [comment]
Thanks for the bug report.

I tried reproducing this with a simple `smugcli mkalbum test/TestAlbum` and didn't encounter any issues. Maybe there is indeed specific permissions in the way with your `Family` folder? Is the Family folder password protected? Is this a folder shared from a different account?

**Comment by firecat53** [comment]
Apparently my API key had the 'add' permission when it needed the 'modify' permission. I was able to change that in the Smugmug settings (Settings->Privacy->Authorized Services). I don't know if that's something that you do/check during the auth process, but it might be worth a mention in the docs or a step during authorization.
