### ISSUE TITLE
Exception when removing a single file

### ISSUE THREAD

**Issue by diekhans** [graveljp/smugcli#37]
`smugcli rm -f 'Clients/ Nov 28, 2024/XXX/_DSC3188.jpg
`
gets the error:

```
Traceback (most recent call last):
  File "/Users/markd/tmp/upenv/bin/smugcli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/markd/tmp/upenv/lib/python3.12/site-packages/smugcli/smugcli.py", line 17, in main
    smugcli_commands.run(sys.argv[1:])
  File "/Users/markd/tmp/upenv/lib/python3.12/site-packages/smugcli/smugcli_commands.py", line 310, in run
    parsed.func(parsed)
  File "/Users/markd/tmp/upenv/lib/python3.12/site-packages/smugcli/smugcli_commands.py", line 163, in <lambda>
    func=lambda a: file_system.rm(a.user, a.force, a.recursive, a.paths))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markd/tmp/upenv/lib/python3.12/site-packages/smugcli/smugmug_fs.py", line 250, in rm
    if recursive or len(node.get_children({'count': 1})) == 0:
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markd/tmp/upenv/lib/python3.12/site-packages/smugcli/smugmug.py", line 256, in get_children
    raise UnexpectedResponseError('Node does not have a "Type" attribute.')
smugcli.smugmug.UnexpectedResponseError: Node does not have a "Type" attribute.

```

Contents of dict with the JSON is:

```
{'AlbumKey': 'JjSZ37',
 'Altitude': 0,
 'ArchivedMD5': 'e2358660515e5ce549dd70c77de660e7',
 'ArchivedSize': 10738817,
 'ArchivedUri': 'https://photos.smugmug.com/photos/XXX/D/i-XXX-D.jpg',
 'CanBuy': True,
 'CanEdit': True,
 'CanShare': True,
 'Caption': '',
 'Collectable': True,
 'Comments': True,
 'ComponentFileTypes': {'Image': ['jpg']},
 'Date': '2024-12-03T01:03:34+00:00',
 'DateTimeOriginal': '2024-11-28T23:39:40+00:00',
 'DateTimeUploaded': '2024-12-03T01:03:34+00:00',
 'EZProject': False,
 'FileName': '_DSC3188.jpg',
 'Format': 'JPG',
 'FormattedValues': {'Caption': {'html': '', 'text': ''},
                     'FileName': {'html': '_DSC3188.jpg',
                                  'text': '_DSC3188.jpg'}},
 'Hidden': False,
 'ImageKey': 'XXX',
 'IsArchive': False,
 'IsVideo': False,
 'KeywordArray': ['Thanksgiving',
                  'widom'],
 'Keywords': 'Thanksgiving; xxx.com; widom',
 'LastUpdated': '2024-12-03T01:03:36+00:00',
 'Latitude': '0',
 'Longitude': '0',
 'Movable': True,
 'Origin': 'Album',
 'OriginalHeight': 8256,
 'OriginalSize': 10738817,
 'OriginalWidth': 5504,
 'PreferredDisplayFileExtension': 'JPG',
 'Processing': False,
 'Protected': True,
 'Serial': 0,
 'ShowKeywords': True,
 'Status': 'Open',
 'SubStatus': 'NFS',
 'ThumbnailUrl': 'https://photos.smugmug.com/photos/xxx/Th/i-XXX-Th.jpg',
 'Title': '',
 'UploadKey': '16026301225',
 'Uri': '/api/v2/album/XXX/image/XXX-0',
 'UriDescription': 'Image from album',
 'Uris': {'Album': {'EndpointType': 'Album',
                    'Locator': 'Album',
                    'LocatorType': 'Object',
                    'Uri': '/api/v2/album/JjSZ37',
                    'UriDescription': 'Album by key'},
          'AlbumImageDownload': {'EndpointType': 'AlbumImageDownload',
                                 'Locator': 'AlbumImageDownload',
                                 'LocatorType': 'Object',
                                 'Uri': '/api/v2/album/JjSZ37/image/XXX-0!download',
                                 'UriDescription': 'Download the image from '
                                                   'the album'},
          'AlbumImageMetadata': {'EndpointType': 'AlbumImageMetadata',
                                 'Locator': 'AlbumImageMetadata',
                                 'LocatorType': 'Object',
                                 'Uri': '/api/v2/album/JjSZ37/image/XXX-0!metadata',
                                 'UriDescription': 'Metadata for AlbumImage'},
          'AlbumImagePricelistExclusions': {'EndpointType': 'AlbumImagePricelistExclusions',
                                            'Locator': 'AlbumImagePricelistExclusions',
                                            'LocatorType': 'Object',
                                            'Uri': '/api/v2/album/JjSZ37/image/XXX-0!pricelistexclusions',
                                            'UriDescription': 'Pricelist '
                                                              'information for '
                                                              'an album image'},
          'AlbumImageShareUris': {'EndpointType': 'AlbumImageShareUris',
                                  'Locator': 'AlbumImageShareUris',
                                  'LocatorType': 'Object',
                                  'Uri': '/api/v2/album/JjSZ37/image/XXX-0!shareuris',
                                  'UriDescription': 'URIs that are useful for '
                                                    'sharing'},
          'ColorImage': {'EndpointType': 'ColorImage',
                         'Locator': 'ColorImage',
                         'LocatorType': 'Object',
                         'Uri': '/api/v2/image/XXX-0!color',
                         'UriDescription': 'Color an image'},
          'CopyImage': {'EndpointType': 'CopyImage',
                        'Uri': '/api/v2/image/XXX-0!copy',
                        'UriDescription': 'Copy an image'},
          'CropImage': {'EndpointType': 'CropImage',
                        'Uri': '/api/v2/image/XXX-0!crop',
                        'UriDescription': 'Crop an image'},
          'Image': {'EndpointType': 'Image',
                    'Locator': 'Image',
                    'LocatorType': 'Object',
                    'Uri': '/api/v2/image/XXX-0',
                    'UriDescription': 'Image by key'},
          'ImageAlbum': {'EndpointType': 'Album',
                         'Locator': 'Album',
                         'LocatorType': 'Object',
                         'Uri': '/api/v2/album/JjSZ37',
                         'UriDescription': 'Album by key'},
          'ImageAlbums': {'EndpointType': 'ImageAlbums',
                          'Locator': 'Album',
                          'LocatorType': 'Objects',
                          'Uri': '/api/v2/image/XXX-0!albums',
                          'UriDescription': 'Albums the image is included in'},
          'ImageComments': {'EndpointType': 'ImageComments',
                            'Locator': 'Comment',
                            'LocatorType': 'Objects',
                            'Uri': '/api/v2/image/XXX-0!comments',
                            'UriDescription': 'Comments on image'},
          'ImageDownload': {'EndpointType': 'ImageDownload',
                            'Locator': 'ImageDownload',
                            'LocatorType': 'Object',
                            'Uri': '/api/v2/image/XXX-0!download',
                            'UriDescription': 'Download image'},
          'ImageMetadata': {'EndpointType': 'ImageMetadata',
                            'Locator': 'ImageMetadata',
                            'LocatorType': 'Object',
                            'Uri': '/api/v2/image/XXX-0!metadata',
                            'UriDescription': 'Metadata for image'},
          'ImageOwner': {'EndpointType': 'User',
                         'Locator': 'User',
                         'LocatorType': 'Object',
                         'Uri': '/api/v2/user/KevinOsbornPhoto',
                         'UriDescription': 'User By Nickname'},
          'ImagePricelistExclusions': {'EndpointType': 'ImagePricelistExclusions',
                                       'Locator': 'ImagePricelistExclusions',
                                       'LocatorType': 'Object',
                                       'Uri': '/api/v2/image/XXX-0!pricelistexclusions',
                                       'UriDescription': 'Pricelist '
                                                         'information for an '
                                                         'image'},
          'ImagePrices': {'EndpointType': 'ImagePrices',
                          'Locator': 'CatalogSkuPrice',
                          'LocatorType': 'Objects',
                          'Uri': '/api/v2/image/XXX-0!prices',
                          'UriDescription': 'Purchasable Skus'},
          'ImageSizeDetails': {'EndpointType': 'ImageSizeDetails',
                               'Locator': 'ImageSizeDetails',
                               'LocatorType': 'Object',
                               'Uri': '/api/v2/image/XXX-0!sizedetails',
                               'UriDescription': 'Detailed size information '
                                                 'for image'},
          'ImageSizes': {'EndpointType': 'ImageSizes',
                         'Locator': 'ImageSizes',
                         'LocatorType': 'Object',
                         'Uri': '/api/v2/image/XXX-0!sizes',
                         'UriDescription': 'Sizes available for image'},
          'LargestImage': {'EndpointType': 'LargestImage',
                           'Locator': 'LargestImage',
                           'LocatorType': 'Object',
                           'Uri': '/api/v2/image/XXX-0!largestimage',
                           'UriDescription': 'Largest size available for '
                                             'image'},
          'PointOfInterest': {'EndpointType': 'PointOfInterest',
                              'Locator': 'PointOfInterest',
                              'LocatorType': 'Object',
                              'Uri': '/api/v2/image/XXX-0!pointofinterest',
                              'UriDescription': 'Point of interest for image'},
          'PointOfInterestCrops': {'EndpointType': 'PointOfInterestCrops',
                                   'Locator': 'PointOfInterestCrops',
                                   'LocatorType': 'List',
                                   'Uri': '/api/v2/image/XXX-0!poicrops',
                                   'UriDescription': 'PointOfInterest Crops '
                                                     'for image'},
          'Regions': {'EndpointType': 'Regions',
                      'Locator': 'Region',
                      'LocatorType': 'Objects',
                      'Uri': '/api/v2/image/XXX-0!regions',
                      'UriDescription': 'Regions for image'},
          'RotateImage': {'EndpointType': 'RotateImage',
                          'Uri': '/api/v2/image/XXX-0!rotate',
                          'UriDescription': 'Rotate an image'}},
 'Watermark': 'No',
 'Watermarked': False,
 'WebUri': 'https://www.foo.com/Clients/Nov-28-2024/fred/n-r73Rz9/i-XXX'}

```

**Comment by graveljp** [comment]
Hi,
I beleive this issue might have been fixed by https://github.com/graveljp/smugcli/pull/25, merged in https://github.com/graveljp/smugcli/commit/f60112dcd901e69bf64e239fd3d93f7db982948e, which was released in Smugcli v1.0.7. Could you try updating Smugcli and see if the issue is resolved?
```
python -m pip install --upgrade smugcli
```

**Comment by diekhans** [comment]
I'm sorry, I can't test this anymore.

**Comment by diekhans** [comment]
close for now, will reopen if it happens again.
